config/routes.rb
Rails.application.routes.draw do

	root "pages#home"
	get "/home" => "pages#home"
	get "/location" => "pages#location"
	
	resources :logins, only: [:new, :create, :destroy]
	resources :signups, only: [:new,:create]
	resources :carts, only: [:index,:create,:destroy]

	get "/carts/checkout" => "carts#checkout"

	resources :categories, only: [:show, :index] do
		resources :subcategories do
			resources :shoes
		end
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availablecolor.rb
class Availablecolor < ActiveRecord::Base

self.table_name = "shoestore.availablecolors"
end

app/models/availablesize.rb
class Availablesize < ActiveRecord::Base

self.table_name = "shoestore.availablesizes"
end

app/models/cart.rb
class Cart < ActiveRecord::Base

self.table_name = "shoestore.orders"
end

app/models/color.rb
class Color < ActiveRecord::Base

self.table_name = "shoestore.colors"
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base

self.table_name = "shoestore.shoes"
end

app/models/signup.rb
class Signup < ActiveRecord::Base

has_secure_password
self.table_name = "shoestore.client"




end

app/models/size.rb
class Size < ActiveRecord::Base

self.table_name = "shoestore.sizes"
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base

self.table_name = "shoestore.category"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


   def current_user
    @current_user ||= Signup.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

 

  def index
     @cart = Cart.where(cid: session[:user_id], flag:1)
  end


  def create
    if session[:user_id]
        cart = Cart.find_by_sql ["Select o.* 
        from shoestore.orders o 
        where o.cid=? and o.sid=? and o.sizeid=? and o.colorid=? and flag=1", session[:user_id],cart_params[:sid],cart_params[:sizeid],cart_params[:colorid] ]

        if cart.empty? 
            cart= Cart.new(cart_params) 
            if cart.save
              flash[:notice] = "Successfully added to your cart"

            else
              flash[:error] = "Please Make sure you checked everything"
            end 
        else
            cart.each do |c|
                c.update(quantity: c.quantity + cart_params[:quantity].to_i)
            end
            flash[:notice] = "Successfully updated your cart"
        end
       
    else 
        flash[:error] = "You have to login to add to cart"
    end
    redirect_to :back
  end

  def cart_params
      params.require(:cart).permit(:sid,:cid,:sizeid,:colorid,:quantity,:flag)
  end

  def destroy
    cart=Cart.find params[:id]
    cart.delete
    redirect_to carts_path
  end

  def checkout

    cart = Cart.where(cid: session[:user_id], flag:1)
 
    cart.each do |c|
      c.update flag: 2
    end 
    
   @cart = Cart.where(cid: session[:user_id], flag:1)
  render "index"
  end




end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		render ("index")
	end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  def new
  end

def create
    user = Signup.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		render("home")

	end

	def location
		render("location")

	end

	def shop 
		render ("shop")
	end


end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController

	def index
		@category= params[:category_id]
		@subcategory= params[:subcategory_id]
		@shoes = 
		Shoe.find_by_sql ["SELECT s.*
			FROM shoestore.shoes s, shoestore.availablesizes a
			Where s.sid=a.sid and quantity>0 and s.catid=?
			group by s.sid", @subcategory]


	end

	def show
		@shoe = Shoe.find params[:id]

		@available = 
		Availablesize.find_by_sql ["SELECT *
			FROM shoestore.availablesizes a,shoestore.sizes s
			Where a.sizeid = s.sizeid and a.sid= ? ", @shoe.sid]

		@availablecolor = 
		Availablecolor.find_by_sql ["SELECT *
			FROM shoestore.availablecolors a, shoestore.colors c
			Where a.colorid = c.colorid and a.sid= ? ", @shoe.sid]


		@shoe = Shoe.find params[:id]
		@cart= Cart.new
		
	end

	def create

		redirect_to category_subcategory_shoes_path
		
	end

	def cart_params
    params.require(:size,:quantity)
  end


end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController


	def new
		@signup = Signup.new
		if params[:message]
			@message = 
			params[:message]
		else
			@message="test"
		end
  	end

    def create
    	@signup = Signup.new(user_params)
    	if user_params[:password_confirmation]=user_params[:password]
		    if @signup.save
		      session[:user_id] = @signup.id
		      redirect_to '/'
		    else
		      render new_signup_path
		    end
		else 
			@message= "Password do not match"
			 render new_signup_path(:message)
		end
    end

private

    def user_params
    params.require(:signup).permit(:fname,:lname,:gender,:dob, :email, :password, :password_confirmation)
  end


end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController


	
	def index

		@category= params[:category_id]
		if @category== "men" then
		@sub = Subcategory.where ismen: true 
	else 
		@sub = Subcategory.where ismen: false 
	end 
		render "index"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/index.html.erb
<section class='shop'>
   <div class="container">
      <div class="col-sm-12">
         <div class="row shoe-text-center">
            <div class="shoe-text-title">
               <h3>Cart</h3>
            </div>
         </div>

        <% if session[:user_id] %>
             <% if  !@cart.empty? %>
         <div class="row">
            <table>
               <tr>
                  <td>Style</td>
                  <td>Color</td>
                  <td>Size</td>
                  <td>Quantity</td>
                  <td>Price</td>
                  <td>Total</td>
               </tr>
               <% @cart.each do |c|
                  
                  shoe=Shoe.find c.sid
                  color= Color.find c.colorid
                  size= Size.find c.sizeid
                      %>
               <tr>
                  <td> <%= image_tag shoe.image+".jpg",  size: "80"%>
                  <%= shoe.name  %></td>
                  <td> <%= color.color  %></td>
                  <td> <%= size.size %></td>
                  <td> <%= c.quantity  %></td>
                  <td> <%= shoe.price  %>$</td>
                  <td>  <%= shoe.price*c.quantity %>$ </td>
                  <td> <%= link_to  image_tag('remove.png',size: "16"), c, data: {method: "delete"} %></td>
               </tr>
               <% end %>
            </table>
         </div>
         <div class="col-sm-3"></div>
         <div class="col-sm-3"></div>
         <div class="col-sm-3"></div>
         <div class="col-sm-3">
         <div class="checkout">
            <%= link_to  "checkout", carts_checkout_path, class: "checkout-btn"%>
         </div>
         </div>
         <% else %>
         Your cart is currently empty.
          <% end %>
          <% else %>
         You need to sign in to view cart.
          <% end %>
      </div>
   </div>
</section>

app/views/categories/index.html.erb
  <section class='shop'>
        <div class="container">
            <div class="col-sm-12">
                <div class="row shoe-text-center">

                    <div class=' shoe-user-title'>
                        <h3 class='shoe-text-center shoe-text-uppercase'>Shop</h3>
                        <hr>
                    </div>
   
                </div>

                <div class="row">

                    <div class='col-sm-4 '>
                        <div class='picture-info' data-scroll-reveal="wait 0.25s, then enter right and move 40px over 1s">
                        <%= link_to image_tag('men.jpg'),  "categories/men/subcategories" %>
                        </div>
                        <div class="info">
                            <h4>Men Shoes</h4>

                        </div>
                    </div>
                     <div class='col-sm-4 '>   </div>
                    <div class='col-sm-4 '>
                        <div class='picture-info' data-scroll-reveal="wait 0.25s, then enter right and move 40px over 1s">
                            <%= link_to image_tag('women.jpg'),  "categories/women/subcategories"  %>
                        </div>
                        <div class="info">
                            <h4>Women Shoes</h4>

                        </div>
                    </div>

                </div>
               
            </div>

        </div>
      
    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= stylesheet_link_tag 'bootstrap.min.css', 'style.css','font-awesome-4.1.0/css/font-awesome.min.css'%>
       
   
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'tss_logo.png' %>
    <title>
        The Shoe Store
    </title>
  </head>

  <body>
     <header class="heading navbar navbar-inverse navbar-fixed-top " role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle togglebutton" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

               <%= link_to image_tag('tss_logo.png', class:"logo"), home_path, class: 'shoe-logo' %>
                
            </div>

            <div class="collapse navbar-collapse menubar">
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "Home", home_path %></li>

                    <!-- <li><%= link_to "Location", location_path %></li> -->

                    <li>  <%= link_to "Shop", categories_path %></li>
                   
<% if current_user %>
 <li><%= link_to "Cart("+ Cart.where(flag: 1,cid: session[:user_id]).count.to_s + ")", carts_path %></li>
 <li><%= link_to "Logout" , login_path(session[:user_id]), data: {method: "delete"}%></li>
<% else %>
   <li><%= link_to "Login", new_login_path %></li>
<% end %>

            
                  
                </ul>
            </div>
        </div>
    </header>

    <%= yield %>


        <!-- <footer class="shoe-contact ">
        <div class="container">
            
            <div class="tittle">
                <h3 class='shoe-text-center shoe-text-uppercase'>Get in touch</h3>
                <hr>
            </div>
            
            <div class="social_icons">
                <ul>
                    <li class="facebook"> <a href="" data-scroll-reveal="wait 0.25s, then enter top and move 40px over 1s"><i class="fa fa-facebook"></i> </a> </li>
                    <li class="twitter"> <a href="" data-scroll-reveal="wait 0.25s, then enter top and move 40px over 1s"><i class="fa fa-twitter"></i> </a> </li>
                    <li class="youtube"> <a href="" data-scroll-reveal="wait 0.25s, then enter top and move 40px over 1s"><i class="fa fa-youtube"></i> </a> </li>
                    <li class="linkedin "> <a href="" data-scroll-reveal="wait 0.25s, then enter top and move 40px over 1s"><i class="fa fa-linkedin"></i> </a> </li>
                </ul>
            </div>
        </div>
        </div>
        <div class="copyrights">
            <div class="container">
                <p class="pull-left">© Shoe Store All Rights Reserved</p>
            </div>
    </footer> -->



    <%= javascript_include_tag 'jquery.js','bootstrap.js','bootstrap.min.js' %>
    <%= javascript_include_tag 'jquery-1.10.2.min.js' %>
    <%= javascript_include_tag 'scrollReveal.js' %>
    <%= javascript_include_tag 'owl.carousel.min.js' %>
    <%= javascript_include_tag 'function.js' %>
  </body>
</html>

app/views/logins/_loginform.html.erb
<%= form_tag '/logins', :class => 'form' do %>

	<div>
		<%= label_tag :email %><br />
		<%= email_field_tag :email, "",:required => true  %>
	</div>

	<div>
		<%= label_tag :password %> <br />
		<%= password_field_tag :password,:required => true%>
	</div>

	<%= submit_tag "Submit", class: "login-submit" %> 
<% end %>

app/views/logins/new.html.erb
<section class='shop'>
        <div class="container">
            <div class="col-sm-12">

<div class="col-sm-4"></div>
<div class="col-sm-4">
 <h3 class='shoe-text-center'>Already have an account?</h3>
                <hr>
<%= render "loginform" %>

<h3 class='shoe-text-center'>Are you new?</h3>
                <hr>

<%= button_to "Sign up here", new_signup_path, :method => "get", class: "login-submit" %>


 </div>
</div>
                </div>

    </section>

app/views/logins/signup.html.erb
<section class='shop'>
        <div class="container">
            <div class="col-sm-12">

<div class="col-sm-4"></div>
<div class="col-sm-4">
 <h3 class='shoe-text-center'>Already have an account?</h3>
                <hr>
<%= render "loginform" %>


 </div>
</div>
                </div>

    </section>

app/views/pages/home.html.erb
  <section class='video'>
        <div class="container">
            <div class="col-sm-12">
                <div class="row">
                    <div class="col-sm-6">
                        <div class='picture-info' data-scroll-reveal="wait 0.25s, then enter right and move 40px over 1s">
                            <%= image_tag('tss_logo.png') %>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class='shoe-user-title'>
                            <h3 class='shoe-text-center shoe-text-uppercase'>about us</h3>
                            <hr>
                        </div>
                        <p>
                            
                            Style. Quality. These two simple words mean everything to us. At The Shoe Store, we are committed to bringing you the best brands from around the world. We carry all sizes and styles, and if you can't find what you're looking for, we'll make sure to find it for you. At The Shoe Store, we help you put your best foot forward.

                        </p>

                        </br>
                         <div class='shoe-user-title'>
                            <h3 class='shoe-text-center shoe-text-uppercase'>Where to find us</h3>
                            <hr>
                            <p class='shoe-text-center'>
                                164 Laurier Str, Ottawa </br>
                                Ontario, Canada</br>
                                K8V 4J4</br>
                                +1 (613) 123 1234</br>
                                contact@theshoestore.ca</br>

                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

app/views/shoes/_shoeform.html.erb
<%= form_for @cart do |f|%>

<%= if session[:user_id] then
f.hidden_field :cid,  :value => session[:user_id]
else 
f.hidden_field :cid,  :value => 0
end %>
<%= f.hidden_field :sid,  :value => @shoe.sid %>
<%= f.hidden_field :flag,  :value => 1 %>
    <p>Price =
        <%= @shoe.price %>$</p>

    <div class="buttons">
        <%= label_tag "Colors" %> <br />

        <% @availablecolor.each do |a|%>
        <%= f.radio_button :colorid, a.colorid,:required => true%> <%=a.color%>
        <img class="circle circle-color-select" data-bgcolor=<%=a.color%>> </img><br />
            <% end %>
            

    </div>
<br />
    <div class="size">
       <%= label_tag "Sizes" %> <br />
       <% @available.each do |a|%>
            <%= f.radio_button :sizeid, a.sizeid, :data => {:quantity => a.quantity}, class: "shoesize",:required => true %><%=a.size%><br />
            <% end %>

            <div class="shoequantity">
            </div>
           

    </div>
    <br>

    <br>

   <% if flash[:notice] -%>
  <p class="notice"><%= flash[:notice] %></p>
<% end -%>
<% if flash[:error] -%>
  <p class="error"><%= flash[:error] %></p>
<% end -%>

<%= submit_tag "Add to cart"%> 


<% end %>

app/views/shoes/index.html.erb
<section class='shop'>
   <div class="container">
      <div class="col-sm-12">
         <div class="row shoe-text-center">
            <div class=' shoe-user-title'>
               <h3 class='shoe-text-center shoe-text-uppercase'><%=@category%> Shoes</h3>
               <hr>
            </div>
         
         </div>
         <div class="row">
            <% @shoes.each do |shoe|%>
            <div class='col-sm-3 '>

              <%= link_to "/categories/"+@category+"/subcategories/"+@subcategory+"/shoes/"+shoe.sid.to_s do %>
               <div class='picture-info' data-scroll-reveal="wait 0.25s, then enter right and move 40px over 1s">
                  
                  <%= image_tag(shoe.image+".jpg") %>
                  <div class="info">
                     <h4><%= shoe.name%></h4>
                     <span><%= shoe.price%>$</span>
                  </div>
               </div>
               <%end %>


            </div>
            <% end %>
         </div>
      </div>
   </div>
</section>

app/views/shoes/show.html.erb
 <section class='shop'>
        <div class="container">
            <div class="col-sm-12">
                <div class="row shoe-text-center">

                    <div class=' shoe-user-title'>
                        <h3 class='shoe-text-center shoe-text-uppercase'><%= @shoe.name %></h3>
                        <hr>
                    </div>
                   
                </div>

                <div class="row">
                <div class="col-sm-6">
    <div class='picture-info' data-scroll-reveal="wait 0.25s, then enter right and move 40px over 1s">
        <%= image_tag(@shoe.image+".jpg") %>
    </div>

</div>
<div class="col-sm-6 shoe-text-center">

                    <%= render "shoeform" %>

                    </div>

                </div>

            </div>
        </div>
        </div>
    </section>

app/views/signups/_signupform.html.erb
<%= form_for @signup do |f| %>


	<div>
		<%= f.label :fname, "First Name" %><br />
		<%= f.text_field :fname,:required => true %>
	</div>

	<div>
		<%= label_tag :lname, "Last Name" %><br />
		<%= f.text_field :lname,:required => true %><br />
	</div>

	<div>
		<br /><%= label_tag :gender, "Gender" %><br />
		
<%= f.radio_button :gender, "M" ,:required => true%>
<%= f.label(:gender_male, "Male") %><br />
<%= f.radio_button :gender, "F" ,:required => true%>
<%= f.label(:gender_female, "Female") %><br />
<%= f.radio_button :gender, "U" ,:required => true%>
<%= f.label(:gender_unassigned, "Prefer not to tell") %>
	</div>



<div><br />
		<%= label_tag :dob, "Date of Birth" %><br />
		<%= f.date_field :dob,:required => true %>
	</div>
	<div>
		<%= label_tag :email, "Email" %><br />
		<%= f.text_field :email,:required => true %>
	</div>

	<div>
		<%= label_tag :gender, "Password" %> <br />
		<%= f.password_field :password,:required => true%>
	</div>
	<div>
		<%= label_tag :password_confirmation, "Confirm Password" %><br />
		<%= f.password_field :password_confirmation,:required => true%>
	</div>

	<%= f.submit "Submit" %> 
<% end %>

app/views/signups/new.html.erb
<section class='shop'>
        <div class="container">
            <div class="col-sm-12">

<div class="col-sm-4"></div>
<div class="col-sm-4">
 <h3 class='shoe-text-center'>Sign up</h3>
                <hr>
<%= render "signupform" %>


 </div>
</div>
                </div>

    </section>

app/views/subcategories/index.html.erb
<section class='shop' >
 <div class="container">
 <div class="col-sm-12">
 <div class="row shoe-text-center">

      <div class=' shoe-user-title'>
                <h3 class='shoe-text-center shoe-text-uppercase'><%=@category%> Shoes</h3>
                <hr>
            </div>
    </div>

<div class="row">
    

<% @sub.each do |sub|%>
             <div class='col-sm-4 '>
                        <div class='picture-info'>
                            <%= link_to image_tag(sub.image), "subcategories/"+sub.catid.to_s+"/shoes" %>
                            <div class="info">
                                <h4><%= sub.nom %></h4>
                            </div>
                        </div>
                    </div>

          <% end %>
                  
                    </div>

  
 
</div>


    </div>
</section>